#!/usr/local/bin/zsh

#Vim and Vundle
if [ ! -e "${ZDOTDIR:-$HOME}/.vimrc" ]; then
  ln -s "${ZDOTDIR:-$HOME}/dotfiles/vim/vimrc" "${ZDOTDIR:-$HOME}/.vimrc"
fi

# Get Vundle and install plugins
if [ ! -d "${ZDOTDIR:-$HOME}/.vim" ]; then
  mkdir -p "${ZDOTDIR:-$HOME}/.vim/bundle"
  git clone https://github.com/VundleVim/Vundle.vim.git "${ZDOTDIR:-$HOME}/.vim/bundle/Vundle.vim"
fi
vim -E -s -c "source ~/.vimrc" -c "PluginClean" -c "PluginInstall" -c "PluginUpdate" -c "qa!"

# Get Prezto
if [ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
else
  cd "${ZDOTDIR:-$HOME}/.zprezto" && git pull && git submodule update --init --recursive
fi

# Get Powerlevel9k ZSH theme
if [ ! -d "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k" ]; then
  git clone https://github.com/bhilburn/powerlevel9k.git  "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k"
  ln -s "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k/powerlevel9k.zsh-theme" "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup"
else
  cd "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k" && git pull && git submodule update --init --recursive
fi

# Symlink custom zsh config files
setopt EXTENDED_GLOB
for customfile in "${ZDOTDIR:-$HOME}"/dotfiles/zsh/*; do
  ln -sf "$customfile" "${ZDOTDIR:-$HOME}/.${customfile:t}"
done

# Symlink default prezto config files
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  if [ ! -e "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]; then
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  fi
done

# Symlink Git config files
if [ ! -e "${ZDOTDIR:-$HOME}/.gitconfig" ]; then
  ln -s "${ZDOTDIR:-$HOME}/dotfiles/git/gitconfig" "${ZDOTDIR:-$HOME}/.gitconfig"
fi

# Symlink editorconfig
if [ ! -e "${ZDOTDIR:-$HOME}/.editorconfig" ]; then
  ln -s "${ZDOTDIR:-$HOME}/dotfiles/editorconfig" "${ZDOTDIR:-$HOME}/.editorconfig"
fi
