#!/usr/local/bin/zsh

#Vim and Vundle
if [ ! -e "${ZDOTDIR:-$HOME}/.vimrc" ]; then
  ln -s "${ZDOTDIR:-$HOME}/dotfiles/vim/vimrc" "${ZDOTDIR:-$HOME}/.vimrc"
fi

# Get Vundle and install plugins
if [ ! -d "${ZDOTDIR:-$HOME}/.vim" ]; then
  mkdir -p "${ZDOTDIR:-$HOME}/.vim/bundle"
  git clone https://github.com/VundleVim/Vundle.vim.git "${ZDOTDIR:-$HOME}/.vim/bundle/Vundle.vim"
fi
#vim -E -s -c "source ~/.vimrc" -c "PluginClean" -c "PluginInstall" -c "PluginUpdate" -c "qa!"

# Get Prezto including Powerlevel9k ZSH theme
if [ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
else
  cd "${ZDOTDIR:-$HOME}/.zprezto" && git pull && git submodule update --init --recursive
fi

# Symlink custom zsh config files
setopt EXTENDED_GLOB
for customfile in "${ZDOTDIR:-$HOME}"/dotfiles/zsh/*; do
  ln -sf "$customfile" "${ZDOTDIR:-$HOME}/.${customfile:t}"
done

# Symlink default prezto config files
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  if [ ! -e "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]; then
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  fi
done

# Include
git config --global include.path "dotfiles/git/gitconfig"

# Symlink editorconfig
if [ ! -e "${ZDOTDIR:-$HOME}/.editorconfig" ]; then
  ln -s "${ZDOTDIR:-$HOME}/dotfiles/editorconfig" "${ZDOTDIR:-$HOME}/.editorconfig"
fi
