#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Add Powerlevel9k mode before loading prezto
POWERLEVEL9K_MODE='awesome-fontconfig'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vi='vim'

# Java & Android studion env variables
export JAVA_HOME="`/usr/libexec/java_home -v '1.8*'`"
export PATH=${JAVA_HOME}/bin:$PATH
export ANDROID_HOME=~/Library/Android/sdk
export PATH="$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools"

# added by Miniconda3 installer
export PATH="/Users/julien/miniconda3/bin:$PATH"

# added node v6
export PATH="/usr/local/opt/node@6/bin:$PATH"

# public IP
alias wanip='dig @resolver1.opendns.com ANY myip.opendns.com +short'
